export const en = {
  header: 'ONE SHOT CAN BE',
  headerGreen: 'YOUR LUCKY DAY',
  headerDesc: 'Participate on our contests and show',
  headerDesc2: 'how good are your photos',
  navLink1: 'ABOUT',
  navLink2: 'CONTACT',
  navLink3: 'RULES',

  weeklyContestTitle: 'NEW WEEKLY',
  weeklyContestTitleGreen: 'CONTESTS',
  weeklyContestPlaceholderName: 'name',
  weeklyContestPlaceholderEmail: 'myaddress@email.com',
  weeklyContestButton: 'NOTIFY ME!',

  howitWorks: 'HOW IT WORKS',
  howitWorksList1: 'Choose one of the listed contests',
  howitWorksList2: 'Pay the value to submit your photos',
  howitWorksList3: 'Upload your photos or send it by email (in case of bank transfer)',
  howitWorksList4: 'Wait until the end of the contest (end or REVIEW phase)',
  howitWorksList5: 'The results will be sent to your email address with the final list of winners and your photo final position. You will also be informed about the judge decision based on this criteria',

  socialTitle: 'GO SOCIAL AND SEE WHAT THEY SAY ABOUT US!',
  help: 'HELP',
  ambassador: 'OUR AMBASSADORS',
  termPolicy: 'Terms & Privacy',

  remainingTime: 'Remaining Time',
  days: 'Days',
  hours: 'Hours',
  photos: 'Photos',
  yourPhotos: 'Your Photos',
  prizeMoney: 'Prize Money',
  uploadNew: 'UPLOAD NEW IMAGES',
  limitMax: 'You can\'t upload more than 10 photos.',
  name: 'Name',
  size: 'Size',
  lastModified: 'Last Modified',
  type: 'Type',
  remove: 'Remove',
  status: 'Status',
  yourImages: 'Your Images',
  noImages1: 'You haven\'t upload any images to this contest yet',
  noImages2: 'You can upload more images from the form above.'
}

export const pt = {
  header: 'UM DISPARO PODE SER',
  headerGreen: 'SEU DIA DE SORTE',
  headerDesc: 'Participe nos nossos concursos e mostre',
  headerDesc2: 'quanto boas são as sua fotos',
  navLink1: 'SOBRE',
  navLink2: 'CONTATO',
  navLink3: 'REGRAS',

  weeklyContestTitle: 'NOVOS SEMANAL',
  weeklyContestTitleGreen: 'CONCURSOS',
  weeklyContestPlaceholderName: 'nome',
  weeklyContestPlaceholderEmail: 'meuenderço@email.com',
  weeklyContestButton: 'AVISA ME!',

  howitWorks: 'HOW IT WORKS',
  howitWorksList1: 'Escolhe um dos concursos listados',
  howitWorksList2: 'Paga o valor para submeter as tuas fotos',
  howitWorksList3: 'Faz o upload das tuas fotos ou envia por email (no caso de regular transferência)',
  howitWorksList4: 'Espera até ao fim do concurso (fim da fase REVIEW)',
  howitWorksList5: 'Os resultados serão enviados para o teu endereço de email com a lista final de vencedores e a posição final da tua foto. Irás receber também os detalhes sobre a decisão do júri com base nestes critérios',

  socialTitle: 'VEJA AS REDES SOCIAIS E O QUE DIZEM SOBRE NÓS!',
  help: 'AJUDA',
  ambassador: 'nosso embaixador',
  termPolicy: 'Termos & Privacidade',

  remainingTime: 'tempo restante',
  days: 'Dias',
  hours: 'Horas',
  photos: 'Fotos',
  yourPhotos: 'Suas fotos',
  prizeMoney: 'Prêmio em dinheiro',
  uploadNew: 'UPLOAD NOVAS IMAGENS',
  limitMax: 'Você não pode fazer upload de mais de 10 fotos.',
  name: 'Nome',
  size: 'Tamanho',
  lastModified: 'Última modificação',
  type: 'Tipo',
  remove: 'Remover',
  status: 'Status',
  yourImages: 'Suas imagens',
  noImages1: 'Você ainda não enviou nenhuma imagem para este concurso',
  noImages2: 'Você pode enviar mais imagens do formulário acima.'
}