export const en = {
  day: 'Day',
  week: 'Week',
  month: 'Month',
  months: 'Months',
  to: 'to',
  langKey: 'en',
  header: 'ONE SHOT CAN BE',
  headerGreen: 'YOUR LUCKY DAY',
  headerDesc: 'Participate on our contests and show',
  headerDesc2: 'how great are your photos',
  navLink1: 'ABOUT',
  navLink2: 'CONTACT',
  navLink3: 'RULES',

  paymentMethod: 'Payment Method',
  iAgree: 'I agree on these',
  pay: 'Pay',
  next: 'NEXT',

  emailValid: 'Please confirm your email by entering the code just sent (check spam), if not received double check the entered email',

  weeklyContestTitle: 'NEW',
  weeklyContestTitleGreen: 'CONTESTS',
  weeklyContestPlaceholderName: 'name',
  weeklyContestPlaceholderEmail: 'myaddress@email.com',
  weeklyContestButton: 'NOTIFY ME!',

  howitWorks: 'HOW IT WORKS',
  howitWorksList1: 'Choose one of the listed contests',
  howitWorksList2: 'Pay the entry fees to submit up to 10 photos',
  howitWorksList3: 'Upload your photos',
  howitWorksList4: 'Wait until the end of the contest (end or REVIEW phase)',
  howitWorksList5: 'The results will be sent to your email address with the final list of winners and your photo final position. You will also be informed about the judge decision based on these',

  socialTitle: 'GO SOCIAL AND SEE WHAT THEY SAY ABOUT US!',
  help: 'HELP',
  ambassador: 'OUR AMBASSADORS',
  termPolicy: 'Terms & Privacy',

  remainingTime: 'Remaining Time',
  days: 'Days',
  hours: 'Hours',
  photos: 'Photos',
  photo: 'photo',
  yourPhotos: 'Your Photos',
  prizeMoney: 'Prize Money',
  uploadNew: 'UPLOAD NEW PHOTOS',
  limitMax: 'You can\'t upload more than ',
  name: 'Name',
  size: 'Size',
  lastModified: 'Last Modified',
  type: 'Type',
  remove: 'Remove',
  status: 'Status',
  yourImages: 'Your Photos',
  noImages1: 'You haven\'t upload any photos to this contest yet',
  noImages2: 'You can upload more photos from the form above.',
  maxLimitNotice: 'Maximum size allowed: 10 mb',

  aboutTitle: 'ABOUT',
  aboutP1: 'EYEOU is a web platform having available photographic contests made from professional photographers to all around photographers.',
  aboutP2: 'It aims to provide this premium service where anyone can use it test their photographic skills by participating on the available contests. Each contest has a specific time for submission and afterwards the review done by the judge, which is set by at least 3 members of our ambassadors. For all the details please check the rules.',
  aboutP3: 'Our team of ambassadors reflects the premium quality of these contests, we have with us the well known and best of professional photographers in Portugal and also with great references overseas, including the portuguese number 1 as traveler photographer.',

  contactTitle: 'CONTACT',
  contactP1: 'You can contact us at:',

  helpTitle: 'HELP',
  helpP1: 'Any question, suggestion you may have please don’t hesitate to send to us your query to:',

  ambsTitle: 'Be Our Ambassador',
  ambsP1: 'If you are already a professional photographer, and you would love to apply to be one of our ambassadors, please feel free to send us your curriculum vitae.',
  ambsP2: 'You can send us',
  ambsLi1: 'a traditional curriculum vitae',
  ambsLi2: 'your linkedin profile',
  ambsLi3: 'your personal website',
  ambsP3: 'to: ',
  ambsP4: 'We will answer you in any case.',

  rulesTitle: 'CONTEST RULES',
  
  rulesSection1: 'RULES',
  rulesP1: 'At any moment it will be running on EYEOU website 6 contests. One is a FREE contest and the other five are entry paid contests. Free contest only allows 1 photo per email address, while paid contest allows to upload up to 10 photos.',
  rulesP2: 'There is a minimum acceptable number of entries (users, or email addresses) required (with few exceptions) to start the contest. If at the end of the submission date, this number is not reached the contest will be cancelled or extended few more days. If the contest is cancelled all the users will receive back the paid fee.',
  rulesP3: 'We can still continue with the contest even if the minimum number of acceptable entries is not reached, that decision will be decided by EYEOU directors, for each case individually.',
  rulesP4: 'Each contest will happen in 3 consecutive phases:',
  rulesStrong1: 'OPEN',
  rulesLi1: 'for submission, period of time when the user can participate and upload up to 10 photos.',
  rulesStrong2: 'REVIEW',
  rulesLi2: 'by chosen judge, after the OPEN phase the contest will transit to the REVIEW phase where the judge (a minimum of 3 of our ambassadors) will be deciding who the winners are.',
  rulesStrong3: 'CLOSED',
  rulesLi3: 'as soon as the judge makes the final decision the results will be sent for all the participants and the contest will be set to CLOSED.',
  
  rulesSection2: 'Contest Times',
  rulesTh1: 'Time duration of the',
  rulesTh2: 'Time duration of the',
  rulesPhase: 'phase',
  rulesTd1: '1 Week ( 7 days, 168 hours)',
  rulesTd2: '3 days ( 72 hours)',
  rulesTd3: '1 Month ( 30 days, 720 hours)',
  rulesTd4: '3 days ( 72 hours)',
  rulesTd5: '3 Months (90 days, 2160 hours)',
  rulesTd6: '5 days ( 72 hours)',
  rulesTd7: '6 Months (180 days, 4320 hours)',
  rulesTd8: '5 days ( 72 hours)',
  rulesTd9: '1 Year (360 days, 8640 hours)',
  rulesTd10: '5 days ( 72 hours)',
  
  rulesSection3: 'Contest Awards, entry fee (in euros €) and minimum required entries',
  rulesTh5: 'Awards',
  rulesTh6: 'Fee',
  rulesTh7: 'Minimum entries',
  rulesFree: 'FREE',
  rulesP5: 'Looking to the second line, we can have a 2500€ contest with an entry fee of 5€ or 15€ or 25€. The value of the entry fee will be linked to the time set for the contest as show in the previous table.',
  
  rulesSection4: 'Winners',
  rulesP6: 'The winners will be decided by the chosen judge for that contest, there will be 3 places available for the winners.',
  rulesP7: 'EYEOU judges will be judging the photos based on the following criteria:',
  rulesLi4: 'technic',
  rulesLi5: 'quality',
  rulesLi6: 'originality',
  rulesLi7: 'creativity',
  rulesP8: 'In accordance with the contest theme.',
  rulesP9: 'When the contest is finished all the submitted photos will have a score.',
  rulesP10: 'The sum of the score from technic, quality, originality and creativity divided by 4 will give the final judge score.',
  rulesP11: 'The sum of the each judge score divided by the number of judges, will give the final score of the photo.',
  rulesP12: 'The photos with the 3 higher final scores will be the winners.',
  rulesP13: 'Each criteria will be rated from 0 to 10 where 10 is the best of that criteria and 0 the worst.',
  rulesP14: 'For instance, on a contest with 3 judges, a photo will be scored like that:',
  rulesLi8: 'Judge 1: technic: 7 quality: 6 originality: 8 creativity: 5 > Final judge score is 6.50',
  rulesLi9: 'Judge 2: technic: 5 quality: 4 originality: 5 creativity: 6 > Final judge score is 5.00',
  rulesLi10: 'Judge 3: technic: 8 quality: 6 originality: 7 creativity: 4 > Final judge score is 6.25',
  rulesP15: 'Final score will be set to 5.92 (we take always the integer part of the division and the following 2 decimals)',
  rulesP16: 'In case of tie, the photo that was submitted first, will be the winner with second precision.',

  rulesSection5: 'Prize money limitations',
  rulesP17: 'The prize money delivered to the winners will be based on the photo final score and the following scale, which allows us to ensure the ultimate quality of our contests:',
  rulesTh3: 'Scores',
  rulesTh4: 'Maximum prize money granted (€)',
  rulesTd12: 'prize money available',
  rulesP18: 'The winners prize money will be as follow (if score allows it or the maximum amount for the given score, as above):'
}

export const pt = {
  week: 'Semana',
  month: 'Mês',
  day: 'Dia',
  months: 'Mêses',
  to: 'a',
  langKey: 'pt',
  header: 'UM DISPARO PODE SER',
  headerGreen: 'SEU DIA DE SORTE',
  headerDesc: 'Participe nos nossos concursos e mostre',
  headerDesc2: 'quanto boas são as sua fotos',
  navLink1: 'SOBRE',
  navLink2: 'CONTATO',
  navLink3: 'REGRAS',

  emailValid: 'Por favor verifique o seu email com o código recebido (veja spam), se não recebeu verifique o se o seu email está correto.',

  weeklyContestTitle: 'NOVOS',
  weeklyContestTitleGreen: 'CONCURSOS',
  weeklyContestPlaceholderName: 'nome',
  weeklyContestPlaceholderEmail: 'meuenderço@email.com',
  weeklyContestButton: 'AVISA ME!',

  paymentMethod: 'Método de pagamento',
  iAgree: 'Eu concordo com estes',
  howitWorks: 'HOW IT WORKS',
  pay: 'PAGAR',
  next: 'PRÓXIMO',
  howitWorksList1: 'Escolhe um dos concursos listados',
  howitWorksList2: 'O número máximo de fotos permitido para upload são 10',
  howitWorksList3: 'Faça o upload das suas fotos',
  howitWorksList4: 'Espere até terminar o concurso (fim da fase de REVISÃO)',
  howitWorksList5: 'Os resultados serão enviados para o seu endereço de email com a lista final de vencedores e a posição final das suas fotos. Receberá também os detalhes sobre a decisão do júri com base nestas',

  socialTitle: 'VEJA AS REDES SOCIAIS E O QUE DIZEM SOBRE NÓS!',
  help: 'AJUDA',
  ambassador: 'nosso embaixador',
  termPolicy: 'Termos & Privacidade',

  remainingTime: 'tempo restante',
  days: 'Dias',
  hours: 'Horas',
  photos: 'Fotos',
  photo: 'foto',
  yourPhotos: 'Suas fotos',
  prizeMoney: 'Prêmio em dinheiro',
  uploadNew: 'UPLOAD NOVAS FOTOS',
  limitMax: 'Você não pode fazer upload de mais de',
  name: 'Nome',
  size: 'Tamanho',
  lastModified: 'Última modificação',
  type: 'Tipo',
  remove: 'Remover',
  status: 'Status',
  yourImages: 'Suas Fotos',
  noImages1: 'Ainda não submeteu fotos para este concurso',
  noImages2: 'Ainda pode fazer upload the mais fotos.',
  maxLimitNotice: 'Máximo tamanho permitido: 10 mb',

  aboutTitle: 'SOBRE',
  aboutP1: 'O EYEOU é uma plataforma web que disponibiliza concursos fotográficos feitos por fotógrafos profissionais para todos os fotógrafos.',
  aboutP2: 'Destina-se a fornecer este serviço premium, onde qualquer pessoa pode usá-lo, testar suas capacidades fotográficas, participando nos concursos disponíveis. Cada concurso tem um tempo específico para submissão e posterior revisão pelo júri, sendo este constituído por no mínimo 3 dos nossos embaixadores. Para todos os detalhes, por favor, veja as regras.',
  aboutP3: 'A nossa equipa de embaixadores reflecte a qualidade premium destes concursos, temos entre nós os mais reconhecidos fotógrafos profissionais em Portugal e também com excelentes referências no exterior, incluindo o português considerado o número 1 em Portugal como fotógrafo viajante.',

  contactTitle: 'CONTACTO',
  contactP1: 'Pode entrar em contacto com a nossa equipa através do seguinte endereço:',

  helpTitle: 'AJUDA',
  helpP1: 'Alguma questão ou sugestão que tenha, não hesite em contactar-nos para:',

  ambsTitle: 'SEJA NOSSO EMBAIXADOR',
  ambsP1: 'Caso já seja um fotógrafo profissional e gostaria de integrar a equipa dos nossos embaixadores, sinta-se à vontade para nos enviar o seu curriculum vitae.',
  ambsP2: 'Pode-nos enviar:',
  ambsLi1: 'Um curriculum vitae tradicional',
  ambsLi2: 'O seu perfil linkedin',
  ambsLi3: 'O seu website profissional',
  ambsP3: 'para: ',
  ambsP4: 'Nós iremos responder-lhe em qualquer dos casos.',

  rulesTitle: 'REGRAS',
  
  rulesSection1: 'Concursos',
  rulesP1: 'A qualquer momento estará em execução no site do EYEOU 6 concursos, 1 deles é um concurso grátis e os outros 5 são concursos pagos. O concurso grátis permite apenas o upload de uma foto por endereço de e-mail, enquanto o concurso pago permite até 10 fotos.',
  rulesP2: 'Há um número mínimo aceitável de entradas por (utilizador / endereço de e-mail) necessários (salvo algumas exceções) para iniciar o concurso. Se no final da data de submissão, esse número não for alcançado, o concurso será cancelado ou será estendido por mais alguns dias a anunciar no momento da decisão. Se o concurso for cancelado, todos os utilizadores receberão de volta o valor pago.',
  rulesP3: 'Podemos continuar com o concurso mesmo que o número mínimo de entradas aceitáveis não seja alcançado, essa decisão será decidida pelos diretores da EYEOU.',
  rulesP4: 'Cada concurso terá 3 fases:',
  rulesStrong1: 'ABERTO',
  rulesLi1: 'para submissão, podendo o utilizador carregar até 10 fotos durante o tempo da duração desta fase.',
  rulesStrong2: 'REVISÃO',
  rulesLi2: 'por um júri, após a fase ABERTO o concurso irá transitar para a fase de REVISÃO onde o júri designado (um mínimo de 3 dos nossos embaixadores) decidirá quem são os vencedores.',
  rulesStrong3: 'FECHADO',
  rulesLi3: 'assim que o júri tomar a decisão final, os resultados serão enviados para todos os participantes e o concurso será FECHADO.',
  
  rulesSection2: 'Tempo do concurso',
  rulesTh1: 'Tempo de duração da fase ABERTO',
  rulesTh2: 'Tempo de duração da fase de REVISÃO',
  rulesPhase: 'fase',
  rulesTd1: '1 Semana ( 7 dias, 168 horas)',
  rulesTd2: '3 dias ( 72 horas)',
  rulesTd3: '1 Mês ( 30 dias, 720 horas) ',
  rulesTd4: '3 dias ( 72 horas)',
  rulesTd5: '3 Meses (90 dias, 2160 horas)',
  rulesTd6: '5 dias ( 120 horas)',
  rulesTd7: '6 Meses (180 dias, 4320 horas)',
  rulesTd8: '5 dias ( 120 horas)',
  rulesTd9: '1 Ano (360 dias, 8640 horas)',
  rulesTd10: '5 dias ( 120 horas)',
  
  rulesSection3: 'Prémios do concurso, valor de entrada (em euros €) e número de entradas mínimo',
  rulesTh5: 'Prémios',
  rulesTh6: 'Entrada',
  rulesTh7: 'entradas mínimas',
  rulesFree: 'FREE',
  rulesP5: 'Olhando para a segunda linha, podemos assim ter um concurso de 2500€ com um valor de entrada de 5€ ou 15€ ou 25€. O valor da entrada está associado ao tempo definido para o concurso, conforme mostrado na tabela anterior.',
  
  rulesSection4: 'Vencedores',
  rulesP6: 'Os vencedores serão decididos pelo júri escolhido para o concurso, haverá 3 lugares disponíveis para os vencedores.',
  rulesP7: 'O júri irá julgar as fotos com base nos seguintes critérios: ',
  rulesLi4: 'técnica',
  rulesLi5: 'qualidade',
  rulesLi6: 'originalidade',
  rulesLi7: 'criatividade',
  rulesP8: 'De acordo com o tema do concurso.',
  rulesP9: 'Quando o concurso terminar, todas as fotos enviadas terão uma pontuação.',
  rulesP10: 'A soma da pontuação da técnica, qualidade, originalidade e criatividade dividida por 4 dará a pontuação final de cada júri.',
  rulesP11: 'A soma da pontuação de cada júri dividida pelo número de júris, dará a pontuação final da foto.',
  rulesP12: 'As fotos com os 3 maiores resultados finais serão os vencedores.',
  rulesP13: 'Cada um destes critérios será classificado de 0 a 10, sendo 10 o melhor e 0 o pior.',
  rulesP14: 'Por exemplo, em um concurso com 3 júris, uma foto será assim classificada:',
  rulesLi8: 'Júri 1: técnica: 7 qualidade: 6 originalidade: 8 criatividade: 5 > Pontuação final do júri é 6,50',
  rulesLi9: 'Júri 2: técnica: 5 qualidade: 4 originalidade: 5 criatividade: 6 > Pontuação final do júri é 5,00',
  rulesLi10: 'Júri 3: técnica: 8 qualidade: 6 originalidade: 7 criatividade: 4 > Pontuação final do júri é 6,25',
  rulesP15: 'A pontuação final será então de 5,92 (parte inteira da divisão e as duas casas decimais seguintes)',
  rulesP16: 'Em caso de empate, a foto que foi submetida em primeiro será a vencedora, com precisão ao segundo.',

  rulesSection5: 'Limitações do prémio em dinheiro',
  rulesP17: 'O prémio em dinheiro a ser entregue aos vencedores será baseado na pontuação final da foto e na escala de qualidade a seguir apresentada, permitindo assim ter uma elevada qualidade nos nossos concursos:',
  rulesTh3: 'Pontuação',
  rulesTh4: 'Prémio máximo garantido',
  rulesTd12: 'prémio máximo disponível',
  rulesP18: 'Os prémios serão distribuídos aos vencedores com base na percentagem apresentada (se a pontuação das fotos vencedoras assim permitir, como indicado acima):'
}